<?php

namespace Bash\TestBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ERepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ERepository extends EntityRepository
{
}
